; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.24629.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Cyborg9\AppData\Local\Temp\.NETFramework,Version=v4.6.2.AssemblyAttributes.cpp"
